export const IPC_CHANNELS = {
  APP_READY: 'app:ready',
  APP_PICK_FOLDER: 'app:pickFolder',
  APP_PICK_FILE: 'app:pickFile',
  APP_SAVE_FILE: 'app:saveFile',
  APP_CHECK_FOR_UPDATES: 'app:checkForUpdates',
  APP_RUN_UPDATE: 'app:runUpdate',
  ADS_LIST: 'ads:list',
  ADS_READ_STREAM: 'ads:readStream',
  ADS_COPY: 'ads:copy',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  SETTINGS_EXPORT: 'settings:export',
  SETTINGS_IMPORT: 'settings:import',
  JOB_LIST: 'job:list',
  JOB_GET: 'job:get',
  JOB_SAVE: 'job:save',
  JOB_DELETE: 'job:delete',
  JOB_IMPORT_JSON: 'job:importJson',
  JOB_IMPORT_INI: 'job:importIni',
  COMPARE_RUN: 'compare:run',
  COMPARE_GET_ROWS: 'compare:getRows',
  COMPARE_CANCEL: 'compare:cancel',
  COMPARE_SET_ROW_INCLUDED: 'compare:setRowIncluded',
  SYNC_RUN: 'sync:run',
  SYNC_CANCEL: 'sync:cancel',
  SYNC_GET_PROGRESS: 'sync:getProgress',
  WATCH_START: 'watch:start',
  WATCH_STOP: 'watch:stop',
} as const

export const EVENT_CHANNELS = {
  SYNC_EVENT: 'sync:event',
} as const
